=== ProgrammeVitam/vitam/sources/functional-administration/functional-administration-common/src/main/resources/json-schema/accession-register-summary.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://example.com/root.json",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "ObjectSize": {
      "type": "object",
      "properties": {
        "ingested": {
          "type": "number"
        },
        "deleted": {
          "type": "number"
        },
        "remained": {
          "type": "number"
        }
      }
    },
    "_id": {
      "type": "string"
    },
    "_tenant": {
      "type": "integer"
    },
    "_v": {
      "type": "integer"
    },
    "OriginatingAgency": {
      "type": "string"
    },
    "TotalObjects": {
      "type": "object",
      "properties": {
        "ingested": {
          "type": "number"
        },
        "deleted": {
          "type": "number"
        },
        "remained": {
          "type": "number"
        }
      }
    },
    "TotalObjectGroups": {
      "type": "object",
      "properties": {
        "ingested": {
          "type": "number"
        },
        "deleted": {
          "type": "number"
        },
        "remained": {
          "type": "number"
        }
      }
    },
    "TotalUnits": {
      "type": "object",
      "properties": {
        "ingested": {
          "type": "number"
        },
        "deleted": {
          "type": "number"
        },
        "remained": {
          "type": "number"
        }
      }
    },
    "CreationDate": {
      "description": "pattern: Date",
      "anyOf": [
        {
          "type": "string",
          "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"
        },
        {
          "type": "string",
          "format": "date-time"
        },
        {
          "type": "string",
          "format": "date-time-vitam"
        }
      ]
    }
  }
}

=== ProgrammeVitam/vitam/sources/integration-test/src/test/resources/preservation/expected/accession_register_ratp_before.json
[{"_id":"aefaaaaaaabf2a33abbckalhycg6lhaaaaaq","OriginatingAgency":"RATP","TotalObjects":{"ingested":8,"deleted":0,"remained":8},"TotalObjectGroups":{"ingested":6,"deleted":0,"remained":6},"TotalUnits":{"ingested":16,"deleted":0,"remained":16},"ObjectSize":{"ingested":36,"deleted":0,"remained":36},"CreationDate":"2018-12-18T09:03:0492","_v":2,"_tenant":0}]

=== ProgrammeVitam/vitam/sources/integration-test/src/test/resources/preservation/expected/accession_register_ratp_after.json
[{"_id":"aefaaaaaaabf2a33abbckalhycg6lhaaaaaq","OriginatingAgency":"RATP","TotalObjects":{"ingested":11.0,"deleted":0.0,"remained":11.0},"TotalObjectGroups":{"ingested":6.0,"deleted":0.0,"remained":6.0},"TotalUnits":{"ingested":16.0,"deleted":0.0,"remained":16.0},"ObjectSize":{"ingested":54.0,"deleted":0.0,"remained":54.0},"CreationDate":"2018-12-18T09:03:04.092","_v":3,"_tenant":0}]

=== ProgrammeVitam/vitam/sources/integration-test/src/test/resources/ingestCleanup/accession_register_summary_3_no_cleanup.json
[
  {
    "OriginatingAgency": "RATP",
    "TotalObjects": {
      "ingested": 5,
      "deleted": 0,
      "remained": 5
    },
    "TotalObjectGroups": {
      "ingested": 3,
      "deleted": 0,
      "remained": 3
    },
    "TotalUnits": {
      "ingested": 9,
      "deleted": 0,
      "remained": 9
    },
    "ObjectSize": {
      "ingested": 9986,
      "deleted": 0,
      "remained": 9986
    },
    "_v": 2,
    "_tenant": 0
  }
]

=== ProgrammeVitam/vitam/sources/integration-test/src/test/resources/preservation/expected/accession_register_FRAN_NP_009913_before.json
[{"_id":"aefaaaaaaabf2a33abbckalhycg7mnyaaaaq","OriginatingAgency":"FRAN_NP_009913","TotalObjects":{"ingested":8,"deleted":0,"remained":8},"TotalObjectGroups":{"ingested":8,"deleted":0,"remained":8},"TotalUnits":{"ingested":14,"deleted":0,"remained":14},"ObjectSize":{"ingested":313294,"deleted":0,"remained":313294},"CreationDate":"2018-12-18T09:03:08.343","_v":2,"_tenant":0}]
