=== ProgrammeVitam/vitam/sources/functional-administration/functional-administration-common/src/main/resources/json-schema/archive-unit-profile.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://example.com/root.json",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "_id": {
      "type": "string"
    },
    "_tenant": {
      "type": "integer"
    },
    "_v": {
      "type": "integer"
    },
    "Identifier": {
      "type": "string"
    },
    "Name": {
      "type": "string"
    },
    "Description": {
      "type": "string"
    },
    "Status": {
      "type": "string",
      "enum": [
        "ACTIVE",
        "INACTIVE"
      ]
    },
    "CreationDate": {
      "description": "pattern: Date",
      "anyOf": [
        {
          "type": "string",
          "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"
        },
        {
          "type": "string",
          "format": "date-time"
        },
        {
          "type": "string",
          "format": "date-time-vitam"
        }
      ]
    },
    "LastUpdate": {
      "description": "pattern: Date",
      "anyOf": [
        {
          "type": "string",
          "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"
        },
        {
          "type": "string",
          "format": "date-time"
        },
        {
          "type": "string",
          "format": "date-time-vitam"
        }
      ]
    },
    "ActivationDate": {
      "description": "pattern: Date",
      "anyOf": [
        {
          "type": "string",
          "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"
        },
        {
          "type": "string",
          "format": "date-time"
        },
        {
          "type": "string",
          "format": "date-time-vitam"
        }
      ]
    },
    "DeactivationDate": {
      "description": "pattern: Date",
      "anyOf": [
        {
          "type": "string",
          "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"
        },
        {
          "type": "string",
          "format": "date-time"
        },
        {
          "type": "string",
          "format": "date-time-vitam"
        }
      ]
    },
	"ControlSchema": {
    	"type": "string"
	},
	"Fields": {
    	"type": "array",
    	"items": {
          "type": "string"
        }
	}
    
  },
  "required": ["_id", "_tenant", "_v", "Identifier", "Name", "Status", "CreationDate", "LastUpdate","ControlSchema"]
}

=== ProgrammeVitam/vitam/sources/common/common-private/src/test/resources/aup-validator/archive_unit_profile_with_properties_field.json
{
	"_id": "aegaaaaaaeeu4mlpab6hialbt7tvkjqaaaaq",
	"Identifier": "AUP_000001",
	"Name": "AUP Name",
	"Description": "Archive unit profil description",
	"Status": "INACTIVE",
	"CreationDate": "2016-12-10T00:00:00.000",
	"LastUpdate": "2018-02-16T18:36:33.444",
	"ActivationDate": "2016-12-10T00:00:00.000",
	"DeactivationDate": "2016-12-10T00:00:00.000",
	"ControlSchema": "{\n  \"$schema\": \"http://json-schema.org/draft-04/schema\",\n  \"type\": \"object\",\n  \"patternProperties\": {\n    \"^_\": {\n      \"description\": \"autorise tous les champs techniques\"\n    },\n    \"^DataObjectReference$\": {},\n    \"^ImplementationVersion$\": {},\n    \"^SedaVersion$\": {},\n    \"^Management$\": {}\n  },\n  \"additionalProperties\": false,\n  \"required\": [\n    \"ArchiveUnitProfile\",\n    \"Description\",\n    \"Title\"\n  ],\n  \"anyOf\": [\n    {\n      \"required\": [\n        \"Description\"\n      ]\n    },\n    {\n      \"required\": [\n        \"Description_\"\n      ]\n    }\n  ],\n  \"properties\": {\n    \"ArchiveUnitProfile\": {\n      \"type\": \"string\"\n    },\n    \"properties\": {\n      \"type\": \"string\"\n    },\n    \"Title\": {\n      \"description\": \"Title : cardinalit√© 1-1 / valeur libre\",\n      \"type\": \"string\"\n    },\n    \"Description\": {\n      \"type\": \"string\",\n      \"minLength\": 1\n    },\n    \"Description_\": {\n      \"type\": \"object\",\n      \"properties\": {\n        \"en\": {\n          \"type\": \"string\",\n          \"minLength\": 1\n        },\n        \"fr\": {\n          \"type\": \"string\",\n          \"minLength\": 1\n        }\n      },\n      \"additionalProperties\": false\n    },\n    \"Title_\": {\n      \"type\": \"object\",\n      \"properties\": {\n        \"en\": {\n          \"type\": \"string\",\n          \"minLength\": 1\n        },\n        \"fr\": {\n          \"type\": \"string\",\n          \"minLength\": 1\n        }\n      },\n      \"additionalProperties\": false\n    }\n  }\n}\n",
	"_tenant": 1,
	"_v": 0
}
