=== ProgrammeVitam/vitam/sources/functional-administration/functional-administration-common/src/main/resources/json-schema/file-rules-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {
    "date-opt-time": {
      "description": "pattern: Date",
      "anyOf": [
        {
          "type": "string",
          "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"
        },
        {
          "type": "string",
          "format": "date-time"
        },
        {
          "type": "string",
          "format": "date-time-vitam"
        }
      ]
    }
  },
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "_id": {
      "type": "string"
    },
    "_tenant": {
      "type": "integer"
    },
    "_v": {
      "type": "integer"
    },
    "RuleId": {
      "type": "string"
    },
    "RuleType": {
      "type": "string"
    },
    "RuleValue": {
      "type": "string"
    },
    "RuleDescription": {
      "type": "string"
    },
    "RuleDuration": {
      "type": "string"
    },
    "RuleMeasurement": {
      "type": "string"
    },
    "CreationDate": {
      "$ref": "#/definitions/date-opt-time"
    },
    "UpdateDate": {
      "$ref": "#/definitions/date-opt-time"
    }
  },
  "required": ["_id", "_tenant", "_v", "RuleId", "RuleType", "RuleValue", "CreationDate", "UpdateDate"],
  "anyOf": [
    {
      "properties": {
        "RuleType": { "enum" : ["HoldRule"] }
      }
    },
    { "required": ["RuleDuration", "RuleMeasurement"] }
  ]
}

=== ProgrammeVitam/vitam/sources/worker/worker-core/src/test/resources/ListArchiveUnitsActionPlugin/updatedRules.json
[
  {
    "_id": "aeaaaaaaaahgyvchabuimak5mlopjbqaaasq",
    "_tenant": 0,
    "RuleId": "ACC-00035",
    "RuleType": "AccessRule",
    "RuleValue": "Communicabilit\u00e9 des documents relatifs aux enqu\u00eates r\u00e9alis\u00e9es par les services de la police judiciaire, aux affaires port\u00e9es devant les juridictions, sous r\u00e9serve des dispositions particuli\u00e8res relatives aux jugements, et \u00e0 l'ex\u00e9cution des d\u00e9cisions de justice dont la communication porte atteinte \u00e0 l'intimit\u00e9 de la vie sexuelle des personnes (date du document)",
    "RuleDescription": "Dur\u00e9e de communicabilit\u00e9 applicable aux documents relatifs aux enqu\u00eates r\u00e9alis\u00e9es par les services de la police judiciaire, aux affaires port\u00e9es devant les juridictions, sous r\u00e9serve des dispositions particuli\u00e8res relatives aux jugements, et \u00e0 l'ex\u00e9cution des d\u00e9cisions de justice dont la communication porte atteinte \u00e0 l'intimit\u00e9 de la vie sexuelle des personnes\nL\u2019\u00e9ch\u00e9ance est calcul\u00e9e \u00e0 partir de la date du document ou du document le plus r\u00e9cent inclus dans le dossier",
    "RuleDuration": "100",
    "RuleMeasurement": "YEAR",
    "CreationDate": "2017-07-21",
    "UpdateDate": "2017-07-21",
    "_v": 1
  },
  {
    "_id": "aeaaaaaaaahgyvchabuimak5mlopjbqaaa5a",
    "_tenant": 0,
    "RuleId": "DIS-1069001",
    "RuleType": "DisseminationRule",
    "RuleValue": "Actes de d\u00e9c\u00e8s",
    "RuleDescription": "D\u00e9lai de diffusion en ligne des actes de d\u00e9c\u00e8s\nL\u2019\u00e9ch\u00e9ance est calcul\u00e9e \u00e0 partir de la date d\u2019enregistrement du d\u00e9c\u00e8s",
    "RuleDuration": "50",
    "RuleMeasurement": "YEAR",
    "CreationDate": "2017-07-21",
    "UpdateDate": "2017-07-21",
    "_v": 1
  },
  {
    "_id": "aeaaaaaaaahgyvchabuimak5mlopjbqaaacq",
    "_tenant": 0,
    "RuleId": "ACC-00003",
    "RuleType": "AccessRule",
    "RuleValue": "Communicabilit\u00e9 des informations portant atteinte \u00e0 la conduite des relations ext\u00e9rieures (date du document)",
    "RuleDescription": "Dur\u00e9e de communicabilit\u00e9 applicable aux informations portant atteinte \u00e0 la conduite des relations ext\u00e9rieures\nL\u2019\u00e9ch\u00e9ance est calcul\u00e9e \u00e0 partir de la date du document ou du document le plus r\u00e9cent inclus dans le dossier",
    "RuleDuration": "25",
    "RuleMeasurement": "YEAR",
    "CreationDate": "2017-07-21",
    "UpdateDate": "2017-07-21",
    "_v": 1
  }
]
